{
 "title": "JMeter_Performance_Testing",
 "description": "JMeter performance testing live results dashboard",
 "time": { "from": "2024-08-15T22:04:47.893Z", "to": "2024-08-16T01:31:23.393Z" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "jmeter,telegraf" },
   {
    "name": "application",
    "query": " from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement_name}\")\r\n  |> group()\r\n  |> distinct(column: \"application\") \r\n  |> drop(columns: [\"_start\", \"_stop\"])"
   },
   {
    "name": "measurement_name",
    "label": "Measurement name",
    "query": "import \"influxdata/influxdb/v1\"\nv1.measurements(bucket: v.bucket)"
   },
   { "name": "send_interval", "query": "${VAR_SEND_INTERVAL}" },
   {
    "name": "site",
    "label": "Site",
    "query": "All_,FHIR,OFF,ACH,GCC,SSH,HA2012293,HA2150032,HA2161708,HA2161366,HA2161715,HA2161711,HA2150585,HA2161263,HA2322733,HA2150594,HA2012341,HA2012347,TrakCare, , ,ping"
   },
   {
    "name": "machine",
    "query": "HA2012293,HA2150032,HA2161708,HA2161366,HA2161715,HA2161711,HA2150585,HA2161263,HA2322733,HA2150594,HA2012341,HA2012347"
   }
  ]
 },
 "panels": [
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "lastValues = from(bucket: \"jmeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"machine\"] == \"TC_HA2012293\" or r[\"machine\"] == \"TC_HA2012347\" or r[\"machine\"] == \"TC_HA2150032\" or r[\"machine\"] == \"TC_HA2161708\" or r[\"machine\"] == \"TC_HA2161366\" or r[\"machine\"] == \"TC_HA2161715\" or r[\"machine\"] == \"TC_HA2161711\" or r[\"machine\"] == \"TC_HA2150585\" or r[\"machine\"] == \"TC_HA2161263\" or r[\"machine\"] == \"TC_HA2322733\" or r[\"machine\"] == \"TC_HA2150594\" or r[\"machine\"] == \"TC_HA2012341\")\n  |> filter(fn: (r) => r[\"_field\"] == \"activeUsers\")\n  |> group(columns: [\"machine\"])\n  |> max()\n\nlastValues\n  |> group()\n  |> sum(column: \"_value\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "iris_license_consumed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"metric\"] == \"iris_license_consumed\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Active Threads per Slave",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"jmeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"machine\"] == \"TC_HA2012293\" or r[\"machine\"] == \"TC_HA2012347\" or r[\"machine\"] == \"TC_HA2150032\" or r[\"machine\"] == \"TC_HA2161708\" or r[\"machine\"] == \"TC_HA2161366\" or r[\"machine\"] == \"TC_HA2161715\" or r[\"machine\"] == \"TC_HA2161711\" or r[\"machine\"] == \"TC_HA2150585\" or r[\"machine\"] == \"TC_HA2161263\" or r[\"machine\"] == \"TC_HA2322733\" or r[\"machine\"] == \"TC_HA2150594\" or r[\"machine\"] == \"TC_HA2012341\" )\n  |> filter(fn: (r) => r[\"_field\"] == \"activeUsers\")\n  |> top(n: 1)"
    }
   ]
  },
  {
   "title": "Total Requests (Combined)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jmeter\")\n  |> filter(fn: (r) => r[\"application\"] == \"${application}\")\n  |> filter(fn: (r) => r[\"transaction\"] =~ /^All*/)\n  |> filter(fn: (r) => r[\"statut\"] == \"all\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> cumulativeSum(columns: [\"_value\"])\n  |> last()\n  |> group()\n  |> sum(column: \"_value\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Requests (TrakCare)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jmeter\")\n  |> filter(fn: (r) => r[\"application\"] == \"${application}\")\n  |> filter(fn: (r) => r[\"transaction\"] =~ /^All_TrakCare.*/)\n  |> filter(fn: (r) => r[\"statut\"] == \"all\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> cumulativeSum(columns: [\"_value\"])\n  |> last()\n  |> group()\n  |> sum(column: \"_value\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Requests (TrakCare)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jmeter\")\n  |> filter(fn: (r) => r[\"application\"] == \"${application}\")\n  |> filter(fn: (r) => r[\"transaction\"] =~ /All_TrakCare.*/)\n  |> filter(fn: (r) => r[\"statut\"] == \"ko\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> cumulativeSum(columns: [\"_value\"])\n  |> last()\n  |> group()\n  |> sum(column: \"_value\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Success Rate % (TrakCare)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "successPercentage = () => {\n\nallCount=from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jmeter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => r[\"application\"] == \"${application}\")\n  |> filter(fn: (r) => r[\"statut\"] == \"all\")\n  |> filter(fn: (r) => r[\"transaction\"] =~ /All_TrakCare.+/)\n  |> group(columns: [\"application\"])\n  |> sum()\n  |> keep(columns: [\"_value\", \"application\"])\n  \nokCount=from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jmeter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => r[\"application\"] == \"${application}\")\n  |> filter(fn: (r) => r[\"statut\"] == \"ok\")\n  |> filter(fn: (r) => r[\"transaction\"] =~ /All_TrakCare.+/)\n  |> group(columns: [\"application\"])\n  |> sum()\n  |> keep(columns: [\"_value\", \"application\"])\n  \n  return join(\n      tables:{allCount:allCount, okCount:okCount},\n      on:[\"application\"]\n    )\n    |> map(fn:(r) => ({\n             \n             percentage: r._value_okCount / r._value_allCount         \n    }))       \n}\n\nsuccessPercentage()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failure Rate % (TrakCare)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "successPercentage = () => {\n\nallCount=from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jmeter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => r[\"application\"] == \"${application}\")\n  |> filter(fn: (r) => r[\"statut\"] == \"all\")\n  |> filter(fn: (r) => r[\"transaction\"] =~ /All_TrakCare.+/)\n  |> group(columns: [\"application\"])\n  |> sum()\n  |> keep(columns: [\"_value\", \"application\"])\n  \nkoCount=from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jmeter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => r[\"application\"] == \"${application}\")\n  |> filter(fn: (r) => r[\"statut\"] == \"ko\")\n  |> filter(fn: (r) => r[\"transaction\"] =~ /All_TrakCare.+/)\n  |> group(columns: [\"application\"])\n  |> sum()\n  |> keep(columns: [\"_value\", \"application\"])\n  \n  return join(\n      tables:{allCount:allCount, koCount:koCount},\n      on:[\"application\"]\n    )\n    |> map(fn:(r) => ({\n             \n             percentage: r._value_koCount / r._value_allCount         \n    }))       \n}\n\nsuccessPercentage()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "iris_license_available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"metric\"] == \"iris_license_available\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Total Requests (FHIR)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jmeter\")\n  |> filter(fn: (r) => r[\"application\"] == \"${application}\")\n  |> filter(fn: (r) => r[\"transaction\"] =~ /^All_FHIR.*/)\n  |> filter(fn: (r) => r[\"statut\"] == \"all\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> cumulativeSum(columns: [\"_value\"])\n  |> last()\n  |> group()\n  |> sum(column: \"_value\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Requests (FHIR)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jmeter\")\n  |> filter(fn: (r) => r[\"application\"] == \"${application}\")\n  |> filter(fn: (r) => r[\"transaction\"] =~ /All_FHIR.*/)\n  |> filter(fn: (r) => r[\"statut\"] == \"ko\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> cumulativeSum(columns: [\"_value\"])\n  |> last()\n  |> group()\n  |> sum(column: \"_value\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Success Rate % (FHIR)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "successPercentage = () => {\n\nallCount=from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jmeter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => r[\"application\"] == \"${application}\")\n  |> filter(fn: (r) => r[\"statut\"] == \"all\")\n  |> filter(fn: (r) => r[\"transaction\"] =~ /All_FHIR.+/)\n  |> group(columns: [\"application\"])\n  |> sum()\n  |> keep(columns: [\"_value\", \"application\"])\n  \nokCount=from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jmeter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => r[\"application\"] == \"${application}\")\n  |> filter(fn: (r) => r[\"statut\"] == \"ok\")\n  |> filter(fn: (r) => r[\"transaction\"] =~ /All_FHIR.+/)\n  |> group(columns: [\"application\"])\n  |> sum()\n  |> keep(columns: [\"_value\", \"application\"])\n  \n  return join(\n      tables:{allCount:allCount, okCount:okCount},\n      on:[\"application\"]\n    )\n    |> map(fn:(r) => ({\n             \n             percentage: r._value_okCount / r._value_allCount         \n    }))       \n}\n\nsuccessPercentage()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failure Rate % (FHIR)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "successPercentage = () => {\n\nallCount=from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jmeter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => r[\"application\"] == \"${application}\")\n  |> filter(fn: (r) => r[\"statut\"] == \"all\")\n  |> filter(fn: (r) => r[\"transaction\"] =~ /All_FHIR.+/)\n  |> group(columns: [\"application\"])\n  |> sum()\n  |> keep(columns: [\"_value\", \"application\"])\n  \nkoCount=from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jmeter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => r[\"application\"] == \"${application}\")\n  |> filter(fn: (r) => r[\"statut\"] == \"ko\")\n  |> filter(fn: (r) => r[\"transaction\"] =~ /All_FHIR.+/)\n  |> group(columns: [\"application\"])\n  |> sum()\n  |> keep(columns: [\"_value\", \"application\"])\n  \n  return join(\n      tables:{allCount:allCount, koCount:koCount},\n      on:[\"application\"]\n    )\n    |> map(fn:(r) => ({\n             \n             percentage: r._value_koCount / r._value_allCount         \n    }))       \n}\n\nsuccessPercentage()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errors By Status Codes",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jmeter\")\n  |> filter(fn: (r) => r[\"application\"] == \"${application}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => exists r[\"responseCode\"])\n  |> group(columns: [\"responseCode\"], mode:\"by\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> count()"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"jmeter\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"machine\"] == \"TC_HA2012293\" or r[\"machine\"] == \"TC_HA2012347\" or r[\"machine\"] == \"TC_HA2150032\" or r[\"machine\"] == \"TC_HA2161708\" or r[\"machine\"] == \"TC_HA2161366\" or r[\"machine\"] == \"TC_HA2161715\" or r[\"machine\"] == \"TC_HA2161711\" or r[\"machine\"] == \"TC_HA2150585\" or r[\"machine\"] == \"TC_HA2161263\" or r[\"machine\"] == \"TC_HA2322733\" or r[\"machine\"] == \"TC_HA2150594\" or r[\"machine\"] == \"TC_HA2012341\" )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"activeUsers\")\r\n  |> aggregateWindow(every: 60s, fn: max, createEmpty: true)"
    }
   ]
  },
  {
   "title": "iris_license_consumed",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"jmeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"metric\"] == \"iris_license_consumed\")\n  |> aggregateWindow(every: 1m, fn: last, createEmpty: true)"
    },
    {}
   ]
  },
  {
   "title": "iris_license_available",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"jmeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"metric\"] == \"iris_license_available\")\n  |> aggregateWindow(every: 1m, fn: last, createEmpty: true)"
    },
    {}
   ]
  },
  {
   "title": "Active Users Vs Response Times (Average)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"jmeter\")\r\n  |> filter(fn: (r) => r._field == \"maxAT\")\r\n  |> keep(columns: [\"_field\", \"_value\", \"_time\"])\r\n  |> aggregateWindow(every: ${send_interval}s, fn: last, createEmpty: true)\r\n  |> set(key: \"_field\", value: \"Active Threads\")"
    },
    {
     "query": "import \"regexp\"\r\nfrom(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement_name}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"avg\")\r\n  |> filter(fn: (r) => r[\"application\"] == \"${application}\")\r\n  |> filter(fn: (r) => r[\"statut\"] == \"all\")\r\n  |> filter(fn: (r) => r.transaction =~ regexp.compile(v: \"${site}\"))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"transaction\"], mode:\"by\")"
    }
   ]
  },
  {
   "title": "Records Locked",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jmeter\")\n  |> filter(fn: (r) => r[\"application\"] == \"${application}\")\n  |> filter(fn: (r) => r[\"statut\"] == \"all\")\n  |> filter(fn: (r) => r[\"transaction\"] =~ /recordIsLocked/)\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> aggregateWindow(every: 60s, fn: sum, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Transactions Response Times Histogram",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jmeter\")\n  |> filter(fn: (r) => r[\"application\"] == \"${application}\")\n  |> filter(fn: (r) => r[\"statut\"] == \"all\")\n  |> filter(fn: (r) => r[\"transaction\"] =~ /${site}+/)\n  |> filter(fn: (r) => r[\"_field\"] == \"avg\")\n  |> top(n: 17000)"
    }
   ]
  },
  {
   "title": "Active Threads Vs Average Transaction Response Times (TrakCare) [${machine}]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 }
  },
  {
   "title": "TrakCare (Avg) - ${machine}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 75 },
   "repeat": "machine",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jmeter\")\n  |> filter(fn: (r) => r[\"application\"] == \"${application}\")\n  |> filter(fn: (r) => r[\"statut\"] == \"all\")\n  |> filter(fn: (r) => r[\"transaction\"] =~ /^${machine}_TrakCare.+/)\n  |> filter(fn: (r) => r[\"_field\"] == \"avg\")\n  |> group(columns: [\"transaction\"], mode:\"by\")"
    },
    {
     "query": "from(bucket: \"jmeter\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"machine\"] == \"TC_${machine}\" )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"activeUsers\")\r\n  |> aggregateWindow(every: 60s, fn: max, createEmpty: true)"
    }
   ]
  },
  { "title": "Error Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Failed Requests Over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jmeter\")\n  |> filter(fn: (r) => r[\"application\"] == \"${application}\")\n  |> filter(fn: (r) => r[\"transaction\"] == \"all\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /countError/)\n  |> set(key: \"_field\", value: \"Failed\") \n  |> top(n: 10000)"
    },
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"jmeter\")\r\n  |> filter(fn: (r) => r._field == \"maxAT\")\r\n  |> keep(columns: [\"_field\", \"_value\", \"_time\"])\r\n  |> aggregateWindow(every: ${send_interval}s, fn: last, createEmpty: true)\r\n  |> set(key: \"_field\", value: \"Active Threads\")"
    }
   ]
  },
  {
   "title": "Error Details",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 95 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jmeter\")\n  |> filter(fn: (r) => r[\"application\"] == \"${application}\")\n  |> filter(fn: (r) => r[\"responseMessage\"] != \"\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> top(n: 5000)"
    }
   ]
  },
  {
   "title": "Response Times Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics",
     "type": "table",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "import \"regexp\"\r\nfrom(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement_name}\")\r\n  |> filter(fn: (r) => r._field == \"count\")\r\n  |> filter(fn: (r) => r[\"statut\"] == \"all\")\r\n  |> filter(fn: (r) => r[\"transaction\"] != \"all\")\r\n  |> filter(fn: (r) => r.transaction =~ regexp.compile(v: \"${site}\"))\r\n  |> keep(columns: [\"_value\", \"transaction\"])\r\n  |> group(columns: [\"transaction\"])\r\n  |> sum()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"# Samples\"})"
      },
      {
       "query": "import \"regexp\"\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement_name}\")\n  |> filter(fn: (r) => r._field == \"avg\")\n  |> filter(fn: (r) => r[\"statut\"] == \"all\")\n  |> filter(fn: (r) => r.transaction =~ regexp.compile(v: \"${site}\"))\n  |> keep(columns: [\"_value\", \"transaction\"])\n  |> group(columns: [\"transaction\"])\n  |> last()\n  |> group()\n  |> rename(columns: {\"_value\": \"Avg\"})"
      },
      {
       "query": "import \"regexp\"\r\nfrom(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement_name}\")\r\n  |> filter(fn: (r) => r._field == \"min\")\r\n  |> filter(fn: (r) => r[\"statut\"] == \"all\")\r\n  |> filter(fn: (r) => r.transaction =~ regexp.compile(v: \"${site}\"))\r\n  |> keep(columns: [\"_value\", \"transaction\"])\r\n  |> group(columns: [\"transaction\"])\r\n  |> min()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"Min\"})"
      },
      {
       "query": "import \"regexp\"\r\nfrom(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement_name}\")\r\n  |> filter(fn: (r) => r._field == \"max\")\r\n  |> filter(fn: (r) => r[\"statut\"] == \"all\")\r\n  |> filter(fn: (r) => r.transaction =~ regexp.compile(v: \"${site}\"))\r\n  |> keep(columns: [\"_value\", \"transaction\"])\r\n  |> group(columns: [\"transaction\"])\r\n  |> max()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"Max\"})"
      },
      {
       "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"jmeter\")\r\n  |> filter(fn: (r) => r._field == \"count\")\r\n  |> filter(fn: (r) => r[\"statut\"] == \"ok\")\r\n  |> filter(fn: (r) => r[\"transaction\"] =~ /^${site}/)\r\n  |> keep(columns: [\"_value\", \"transaction\"])\r\n  |> group(columns: [\"transaction\"])\r\n  |> sum()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"# Pass\"})"
      },
      {
       "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"jmeter\")\r\n  |> filter(fn: (r) => r._field == \"count\")\r\n  |> filter(fn: (r) => r[\"statut\"] == \"ko\")\r\n  |> filter(fn: (r) => r[\"transaction\"] =~ /^${site}/)\r\n  |> keep(columns: [\"_value\", \"transaction\"])\r\n  |> group(columns: [\"transaction\"])\r\n  |> sum()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"# Fail\"})"
      },
      {
       "query": "import \"regexp\"\r\ncountAll = from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement_name}\")\r\n  |> filter(fn: (r) => r._field == \"count\")\r\n  |> filter(fn: (r) => r[\"statut\"] == \"all\")\r\n  |> filter(fn: (r) => r.transaction =~ regexp.compile(v: \"${site}\"))\r\n  |> group(columns: [\"transaction\"])\r\n  |> sum()\r\n  |> group()\r\n  |> toFloat()\r\n  |> keep(columns: [\"_value\", \"transaction\"])\r\n\r\ncountError = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"jmeter\")\r\n  |> filter(fn: (r) => r._field == \"count\")\r\n  |> filter(fn: (r) => r[\"statut\"] == \"ko\")\r\n  |> filter(fn: (r) => r[\"transaction\"] != \"all\")\r\n  |> group(columns: [\"transaction\"])\r\n  |> sum()\r\n  |> group()\r\n  |> toFloat()\r\n  |> keep(columns: [\"_value\", \"transaction\"])\r\n\r\njoin(\r\n      tables:{countAll:countAll, countError:countError},\r\n      on:[\"transaction\"]\r\n    )\r\n    |> map(fn:(r) => ({\r\n             transaction: r.transaction,\r\n             ErrorRate: r._value_countError / r._value_countAll         \r\n}))   "
      }
     ]
    }
   ]
  },
  {
   "title": "Disabled",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 },
   "collapsed": true,
   "panels": [
    { "title": "Active Users", "type": "timeseries", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 }, "fieldConfig": { "defaults": { "unit": "none" } } },
    {
     "title": "Patients Demographic Screen per minute (Passed)",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jmeter\")\n  |> filter(fn: (r) => r[\"application\"] == \"${application}\")\n  |> filter(fn: (r) => r[\"statut\"] == \"ok\")\n  |> filter(fn: (r) => r[\"transaction\"] =~ /All_TrakCare_.+05_SelectPatientDemographic/)\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> aggregateWindow(every: 60s, fn: sum, createEmpty: true)"
      }
     ]
    },
    {
     "title": "Patients Demographic Screen per minute (Failed)",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 104 }
    },
    {
     "title": "Active Users",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 112 },
     "targets": [
      {
       "query": "from(bucket: \"jmeter\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"machine\"] == \"TC_HA2012293\" or r[\"machine\"] == \"TC_HA2012347\" or r[\"machine\"] == \"TC_HA2150032\" or r[\"machine\"] == \"TC_HA2161708\" or r[\"machine\"] == \"TC_HA2161366\" or r[\"machine\"] == \"TC_HA2161715\" or r[\"machine\"] == \"TC_HA2161711\" or r[\"machine\"] == \"TC_HA2150585\" or r[\"machine\"] == \"TC_HA2161263\" or r[\"machine\"] == \"TC_HA2322733\" or r[\"machine\"] == \"TC_HA2150594\" or r[\"machine\"] == \"TC_HA2012341\" )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"activeUsers\")\r\n  |> aggregateWindow(every: 60s, fn: max, createEmpty: true)"
      }
     ]
    }
   ]
  }
 ]
}